### ISSUE TITLE
Blank white LCD and no HID connection

### ISSUE THREAD

**Issue by nick-parker** [zmorph/Smoothieware-ZMorph-fork#2]
When the Zmorph powers up in any configuration (usb power only, AC power only, both, and usb+ac+ethernet connected) the LCD lights up but only displays a blank white screen. The single extruder tool head is mounted right now and the light on there blinks rapidly. Pressing reset, or power cycling makes the light blink slowly for a little then return to its previous state.

Connecting to a computer via USB causes the light on the toolhead to blink more slowly, and the machine mounts as a storage device, but we can't use HID connection in voxelizer. We haven't attempted Telnet yet, but attempting HID yields "an unhandled exception has occurred." with no further feedback.

After this issue developed I followed your procedure to update the firmware to the latest version, which succeeded, but the machine is in the same state.

I've also checked the connection to the LCD, and it appears to be fine.

Supposedly the machine had content on the LCD when they first unboxed it a couple days ago, and they were able to jog the axes. I'll ask around to get some more exact history of what they did to it tomorrow, but i'm really not sure what could be going wrong because they've barely touched the hardware, and the firmware update should've wiped any software issues.

**Comment by zmorph** [comment]
Hi Nick,
You've lost your config file. Did you make backup of all the files on SD 
? If not, I will send it to you.

best regards

Przemek Jaworski
CEO & Founder

www.zmorph3d.com

W dniu 2015-02-19 o 22:17, nick-parker pisze:

**Comment by cederom** [comment]
@nick-parker take out the card from Zmorph3D, plug into local computer, format SD card (FAT32) and upload new firmware+configuration file on SD. blank LCD means problems with firmware/configuration :-)

**Comment by nick-parker** [comment]
Could you send or link your default config? I have a copy of the state the config was in when I first got to the printer, but someone probably modified it before then.

Thanks for the help

**Comment by cederom** [comment]
yea they should put default config with the firmware inside ZIP file not just bare bin file :-) :-)

**Comment by nick-parker** [comment]
Alright we got it working. I reformatted the SD card and put firmware.bin into it with the config that was already on the printer. I didn't zip them or put them in any file structures on the card.

When I turned the printer on with the card back in it it started working perfectly, but pressing the reset button under any circumstances seems to return it to the broken state.

We know how to work around it now though, just avoid reset and everything else works great. Thanks for the help!

**Comment by cederom** [comment]
I was referring to the firmware package on the Zmorph3D server, which would be nice to get as ZIP with firmware binary and default configuration file :-)

**Comment by cederom** [comment]
At first run, when you put a fresh SD card into the printer with new firmware, Smoothieboard needs to read the firmware binary, so it takes a short while and you should not interrupt the process with reset :-)

Good to head you made it :+1:
